services:
  app:
    container_name: caseManagement-Frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://192.168.100.6:8080
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.100.6:8080